const ALL = document.getElementsByTagName("body");
const CONTAINER = document.querySelector("#container");
const LOGIN = document.querySelector("#conteudo > .logon");
const RODAPE = document.querySelector("#container > #rodape");
const CONTEUDO = document.querySelector("#container > #conteudo");
const INFO_USUARIO = document.querySelector("#painel-usuario > #info-usuario");
const MENU_USUARIO = document.querySelector("#painel-usuario > #menu-usuario");
const NOTICIAS = document.querySelector("#main-docente #noticias-portal");
const TURMAS_PORTAL = document.querySelector("#turmas-portal");
const PERFIL_DOCENTE = document.querySelector("#perfil-docente");
const MENU = document.querySelectorAll('[id*="menu_form_menu_discente"]');
